version: '3.9'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example_password
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: example_password
    ports:
      - "8080:80"
    depends_on:
      - db
  jena:
    image: stain/jena-fuseki
    restart: always
    environment:
      ADMIN_PASSWORD: example_password
    volumes:
      - ./data:/fuseki
    ports:
      - "3030:3030"
  fusekiadmin:
    image: stain/jena-fuseki
    restart: always
    entrypoint: sh -c "until nc -z jena 3030; do sleep 1; done; /jena-fuseki-1.3.1/fuseki-server --port=3031 --update --mem /ds"
    environment:
      ADMIN_PASSWORD: example_password
    ports:
      - "8081:3031"
    depends_on:
      - jena
